### ISSUE TITLE
Alienware 13R2 - kinda working

### ISSUE THREAD

**Issue by mungewell** [trackmastersteve/alienfx#10]
The 13R2 only has 8 zones, setup as per attachment.
[controller_13R2.py.zip](https://github.com/ashwinm76/alienfx/files/629217/controller_13R2.py.zip)

There is a problem that if the other zones are not defined then an error is thrown.

    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 754, in run
        self.__target(*self.__args, **self.__kwargs)
      File "build/bdist.linux-x86_64/egg/alienfx/ui/gtkui/gtkui.py", line 211, in set_theme
        self.controller.set_theme(self.themefile)
      File "build/bdist.linux-x86_64/egg/alienfx/core/controller.py", line 262, in set_theme
        cmds = self._make_zone_cmds(themefile, state_name)
      File "build/bdist.linux-x86_64/egg/alienfx/core/controller.py", line 217, in _make_zone_cmds
        zone_codes = self._get_zone_codes(themefile.get_zone_names(item))
      File "build/bdist.linux-x86_64/egg/alienfx/core/controller.py", line 161, in _get_zone_codes
        zones |= self.zone_map[zone]
    KeyError: u'Left Speaker'

Unfortunately having them defined means that they show up on the list on usable zone...
Simon

**Comment by ashwinm76** [comment]
Simon,

  sorry for the delayed reply. I haven't used Linux (and my Alienware M14x) for ages now, so I wont be able to provide any active support. However, I welcome pull requests with support for new Alienware models. I've merged your recent pull request, thanks for that!

- Ashwin

**Comment by trackmastersteve** [comment]
@mungewell 

I've been trying to do some research on the zones for the m13xR2 with no luck so far. But I'll keep trying...

**Comment by trackmastersteve** [comment]
@mungewell 

Did you ever get alienfx working on your m13xr2?
