### ISSUE TITLE
Alienfx not able to detect zones

### ISSUE THREAD

**Issue by t0m5k1** [trackmastersteve/alienfx#127]
### 1. Expected behavior.

Alenfx detecting zones

### 2. Actual behavior.
It fails to detect zones:
```❯ alienfx
You are running alienfx under Python-Version: 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801]
ERROR:root:No Alien FX controller, defined by a supported model, found!
would you like to perform a zonescan? (y/n):y
Performing zonescan...
Welcome. This will help you to scan for alienfx-controllers and their lighting zones.
Traceback (most recent call last):
  File "/usr/bin/alienfx", line 33, in <module>
    sys.exit(load_entry_point('alienfx==2.4.0', 'console_scripts', 'alienfx')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/alienfx/ui/console/main.py", line 81, in start
    doZonescan()
  File "/usr/lib/python3.11/site-packages/alienfx/ui/console/main.py", line 64, in doZonescan
    zonescan.scan()
  File "/usr/lib/python3.11/site-packages/alienfx/core/zonescanner.py", line 134, in scan
    for controller in afxcontroldevs:
TypeError: 'NoneType' object is not iterable
```
### 3. Steps to reproduce the problem.
reinstall alienfx and reboot 

### 4. Specifications like the version of the project, install method, operating system, and hardware.

- Project Version: 2.4.0
- Operating System: archlinux (6.5.4-arch2-1)
- Hardware Version: Alienware R10 0TYR0X (Ryzen 7 5800X, 6700 XT)
Installed via AUR: https://aur.archlinux.org/packages/alienfx

Additional Info:

```
❯ lsusb -vvvt
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 10000M
    ID 1d6b:0003 Linux Foundation 3.0 root hub
    /sys/bus/usb/devices/usb4  /dev/bus/usb/004/001
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
    /sys/bus/usb/devices/usb3  /dev/bus/usb/003/001
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/8p, 10000M
    ID 1d6b:0003 Linux Foundation 3.0 root hub
    /sys/bus/usb/devices/usb2  /dev/bus/usb/002/001
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/14p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
    /sys/bus/usb/devices/usb1  /dev/bus/usb/001/001
    |__ Port 2: Dev 2, If 0, Class=Human Interface Device, Driver=usbhid, 12M
        ID 1e7d:2cee ROCCAT Kova 2016 Gray Mouse
        /sys/bus/usb/devices/1-2  /dev/bus/usb/001/002
    |__ Port 2: Dev 2, If 1, Class=Human Interface Device, Driver=usbhid, 12M
        ID 1e7d:2cee ROCCAT Kova 2016 Gray Mouse
        /sys/bus/usb/devices/1-2  /dev/bus/usb/001/002
    |__ Port 7: Dev 3, If 0, Class=Human Interface Device, Driver=usbhid, 12M
        ID 0c45:5004 Microdia Redragon Mitra RGB Keyboard
        /sys/bus/usb/devices/1-7  /dev/bus/usb/001/003
    |__ Port 7: Dev 3, If 1, Class=Human Interface Device, Driver=usbhid, 12M
        ID 0c45:5004 Microdia Redragon Mitra RGB Keyboard
        /sys/bus/usb/devices/1-7  /dev/bus/usb/001/003
    |__ Port 9: Dev 4, If 0, Class=Wireless, Driver=btusb, 12M
        ID 8087:0029 Intel Corp. AX200 Bluetooth
        /sys/bus/usb/devices/1-9  /dev/bus/usb/001/004
    |__ Port 9: Dev 4, If 1, Class=Wireless, Driver=btusb, 12M
        ID 8087:0029 Intel Corp. AX200 Bluetooth
        /sys/bus/usb/devices/1-9  /dev/bus/usb/001/004
```
When I boot to windows I'm unable to control the lights via AWCC, This has been since trying AlienFX, event logs yields nothing of use. I also see 2 unknown USB devices in device manager.

**Comment by JustCryen** [comment]
It might not be a solution to your problem but have you tried OpenRGB?  
I've been able to use it to change colors on my Alienware m15 R1 while AlienFX also had issued detecting zones on Linux.

**Comment by t0m5k1** [comment]
Weirdness.
I recently re-pasted my CPU and had a general clean out of the case (I own a cat!) and after the brief rebuild and power on all seems to be working!!

I've no idea what actually went wrong with the lighting but am just happy it seems to function as normal and this app is the best for this ...just simplicity.

Next up sorting fan control under linux for this I have odd sensors
