### ISSUE TITLE
ModuleNotFoundError encountered on program start.

### ISSUE THREAD

**Issue by rangicus** [trackmastersteve/alienfx#131]
### 1. Expected behavior.

- Execution of the program.

### 2. Actual behavior.

> $ alienfx
Traceback (most recent call last):
  File "/usr/local/bin/alienfx", line 33, in <module>
    sys.exit(load_entry_point('alienfx==2.4.2', 'console_scripts', 'alienfx')())
  File "/usr/local/bin/alienfx", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/alienfx-2.4.2-py3.10.egg/alienfx/ui/console/__init__.py", line 2, in <module>
  File "/usr/local/lib/python3.10/dist-packages/alienfx-2.4.2-py3.10.egg/alienfx/ui/console/main.py", line 31, in <module>
  File "/home/xavier/.local/lib/python3.10/site-packages/pkg_resources.py", line 29, in <module>
    import symbol
ModuleNotFoundError: No module named 'symbol'

### 3. Steps to reproduce the problem.

- Install dependencies as written in the installation section.
- Install python requirements from the requirements.txt file.
- `$ sudo python setup.py install`
- `$ sudo python setup.py install_data`
- `$ alienfx`

### 4. Specifications like the version of the project, install method, operating system, and hardware.

- Project Version: 6910db0
- Operating System: Pop!_OS 22.04 LTS
- Hardware Version: Alienware 17 R4

**Comment by trackmastersteve** [comment]
This is what I found online: https://stackoverflow.com/questions/70836444/no-module-named-symbol
The problem may be in the version of setuptools you are running?
