### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by trackmastersteve** [trackmastersteve/alienfx#15]
On Arch Linux running python3.6 I have run into this error:

> alienfx --help
Traceback (most recent call last):
  File "/usr/bin/alienfx", line 11, in <module>
    load_entry_point('alienfx==2.0.6', 'console_scripts', 'alienfx')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/alienfx-2.0.6-py3.6.egg/alienfx/ui/console/__init__.py", line 1, in <module>
ModuleNotFoundError: No module named 'main'

**Comment by trackmastersteve** [comment]
I can't get the GUI to load as well on this box.

**Comment by trackmastersteve** [comment]
Fixed this by installing the missing dependancies.
