### ISSUE TITLE
no module named builtins

### ISSUE THREAD

**Issue by Null-cm** [trackmastersteve/alienfx#33]
Hello I'm on a clean install of an M14x R2 with ubuntu 16.10

I believe you need to add pip install future to the requirements.

also the program fails on my M14x R2

**Comment by TheOmegaPope** [comment]
I am on a clean install of Ubuntu 17.X as anything less doesn't load on my new hardware.
I am getting the exact same message, See final line below.
(i also agree with the PIP comment)
Clean install done entirely to get your program working. Seems like a call to a missing file or missing dependency. Any thoughts? 

Traceback (most recent call last):
  File "/usr/local/bin/alienfx", line 11, in <module>
    load_entry_point('alienfx==2.1.1', 'console_scripts', 'alienfx')()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/alienfx/ui/console/__init__.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/alienfx/ui/console/main.py", line 35, in <module>
  File "build/bdist.linux-x86_64/egg/alienfx/core/prober.py", line 32, in <module>
ImportError: No module named builtins

**Comment by TheOmegaPope** [comment]
I fixed my own error by looking at other github projects

The problem is your setup needs to include "pip install future"

This fixes the builtins dependency error

**Comment by trackmastersteve** [comment]
I've added "pip install future" to the dependencies list. Thank you for pointing that out.
