### ISSUE TITLE
XPS 730x -  "TypeError: 'NoneType' object is not iterable" on run

### ISSUE THREAD

**Issue by StephenAkers** [trackmastersteve/alienfx#60]
$ alienfx
You are running alienfx under Python-Version: 3.6.7 (default, Oct 22 2018, 11:32 :17)
[GCC 8.2.0]
ERROR:root:No Alien FX controller, defined by a supported model, found!
would you like to perform a zonescan? (y/n):y
Performing zonescan...
Welcome. This will help you to scan for alienfx-controllers and their lightning zones.
Traceback (most recent call last):
  File "/usr/local/bin/alienfx", line 11, in <module>
    load_entry_point('alienfx==2.3.4', 'console_scripts', 'alienfx')()
  File "/usr/local/lib/python3.6/dist-packages/alienfx-2.3.4-py3.6.egg/alienfx/u                         i/console/main.py", line 81, in start
  File "/usr/local/lib/python3.6/dist-packages/alienfx-2.3.4-py3.6.egg/alienfx/u                         i/console/main.py", line 64, in doZonescan
  File "/usr/local/lib/python3.6/dist-packages/alienfx-2.3.4-py3.6.egg/alienfx/c                         ore/zonescanner.py", line 139, in scan
TypeError: 'NoneType' object is not iterable

Followed readme to install.

- Operating System:
Ubuntu 18.04.1
- Hardware:
xps 730x

**Comment by trackmastersteve** [comment]
Does the XPS 730x have an AlienFX chip?

**Comment by StephenAkers** [comment]
How can I check for it?
