### ISSUE TITLE
AttributeError: 'HTMLParser' object has no attribute 'unescape'

### ISSUE THREAD

**Issue by WillNilges** [trackmastersteve/alienfx#87]
### 1. Expected behavior.

- When installing the application on Fedora, the installation completes successfully.

### 2. Actual behavior.

```
[wilnil@devbox01 alienfx]$  pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting pyusb==1.0.2
  Downloading pyusb-1.0.2.tar.gz (54 kB)
     |████████████████████████████████| 54 kB 1.0 MB/s 
Collecting setuptools==40.0.0
  Downloading setuptools-40.0.0-py2.py3-none-any.whl (567 kB)
     |████████████████████████████████| 567 kB 4.1 MB/s 
Collecting future==0.16.0
  Downloading future-0.16.0.tar.gz (824 kB)
     |████████████████████████████████| 824 kB 23.8 MB/s 
Using legacy 'setup.py install' for pyusb, since package 'wheel' is not installed.
Using legacy 'setup.py install' for future, since package 'wheel' is not installed.
Installing collected packages: pyusb, setuptools, future
  Attempting uninstall: pyusb
    Found existing installation: pyusb 1.1.0
    Uninstalling pyusb-1.1.0:
      Successfully uninstalled pyusb-1.1.0
    Running setup.py install for pyusb ... done
  Attempting uninstall: future
    Found existing installation: future 0.18.2
    Uninstalling future-0.18.2:
      Successfully uninstalled future-0.18.2
    Running setup.py install for future ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y90l6i3u/future/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y90l6i3u/future/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ozwy5fov/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/wilnil/.local/include/python3.9/future
         cwd: /tmp/pip-install-y90l6i3u/future/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/wilnil/.local/lib/python3.9/site-packages/setuptools/__init__.py", line 14, in <module>
        from setuptools.dist import Distribution, Feature
      File "/home/wilnil/.local/lib/python3.9/site-packages/setuptools/dist.py", line 24, in <module>
        from setuptools.depends import Require
      File "/home/wilnil/.local/lib/python3.9/site-packages/setuptools/depends.py", line 7, in <module>
        from .py33compat import Bytecode
      File "/home/wilnil/.local/lib/python3.9/site-packages/setuptools/py33compat.py", line 55, in <module>
        unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
    AttributeError: 'HTMLParser' object has no attribute 'unescape'
    ----------------------------------------
  Rolling back uninstall of future
  Moving to /home/wilnil/.local/bin/futurize
   from /tmp/pip-uninstall-f7xkqqvu/futurize
  Moving to /home/wilnil/.local/bin/pasteurize
   from /tmp/pip-uninstall-f7xkqqvu/pasteurize
  Moving to /home/wilnil/.local/lib/python3.9/site-packages/future-0.18.2-py3.9.egg-info
   from /home/wilnil/.local/lib/python3.9/site-packages/~uture-0.18.2-py3.9.egg-info
  Moving to /home/wilnil/.local/lib/python3.9/site-packages/future/
   from /home/wilnil/.local/lib/python3.9/site-packages/~uture
  Moving to /home/wilnil/.local/lib/python3.9/site-packages/libfuturize/
   from /home/wilnil/.local/lib/python3.9/site-packages/~ibfuturize
  Moving to /home/wilnil/.local/lib/python3.9/site-packages/libpasteurize/
   from /home/wilnil/.local/lib/python3.9/site-packages/~ibpasteurize
  Moving to /home/wilnil/.local/lib/python3.9/site-packages/past/
   from /home/wilnil/.local/lib/python3.9/site-packages/~ast
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y90l6i3u/future/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y90l6i3u/future/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ozwy5fov/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/wilnil/.local/include/python3.9/future Check the logs for full command output.
```

### 3. Steps to reproduce the problem.

- Clean install of Fedora 33
- Go through installation steps
- Die on `pip install -r requirements.txt`

### 4. Specifications like the version of the project, install method, operating system, and hardware.

- Project Version: 6ec9d31c5687626167cbc9680c65b0505f4de873
- Operating System: Fedora 33
- Hardware Version: Alienware Aurora R4

**Comment by WillNilges** [comment]
Apparently, this is a thing on Python 3.9

https://github.com/coursera-dl/coursera-dl/issues/778

I got time right now, so I might look into this a bit.

**Comment by WillNilges** [comment]
I think pacifically, the issue lies with `setuptools`.

**Comment by WillNilges** [comment]
Got around it by using 3.8 in a `pyenv`
