### ISSUE TITLE
ModuleNotFoundError: No module named 'alienfx.core.controller_13r3'

### ISSUE THREAD

**Issue by piraeusstef** [trackmastersteve/alienfx#93]
Getting this error on AlienWare M11XR3  - It was working perfectly with Fedora 32 but fails on 33

Traceback (most recent call last):
  File "/usr/local/bin/alienfx", line 33, in <module>
    sys.exit(load_entry_point('alienfx==2.3.5', 'console_scripts', 'alienfx')())
  File "/usr/local/bin/alienfx", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/alienfx-2.3.5-py3.9.egg/alienfx/ui/console/__init__.py", line 2, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/alienfx-2.3.5-py3.9.egg/alienfx/ui/console/main.py", line 33, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/alienfx-2.3.5-py3.9.egg/alienfx/core/prober.py", line 47, in <module>
ModuleNotFoundError: No module named 'alienfx.core.controller_13r3'

Thanks

**Comment by trackmastersteve** [comment]
The Fedora update might have deleted some of the files. Just try and reinstall alienfx and see if that fixes it.

**Comment by elliejs** [comment]
the 13r3 controller is not within the core package. There's controller_m13xr3, but not controller_13r3. Notably, only _17r[1/3] exist as the _# controllers (without m#)

**Comment by elliejs** [comment]
Ok it looks like prober is the problematic package which still imports 13r3, but that controller isnt in alienfx.core

**Comment by piraeusstef** [comment]
No luck - Re-installed all  still the same errors .
Installation went through without any problem .
Since I have intact the Disk with Fedora 32 I will start looking for
differences.
Thank you for taking your time .

**Comment by goldyfruit** [comment]
Same on Ubuntu 20.10

**Comment by trackmastersteve** [comment]
I think i found and fixed the bug. Try to download and reinstall it now.

**Comment by piraeusstef** [comment]
Yes you did it works now.
Thank you very much for your effort.

**Comment by trackmastersteve** [comment]
No problem!

**Comment by thaddeusc1** [comment]
@trackmastersteve—it looks like this issue is present in the most current release—i.e., v2.3.5 at the time I'm re-opening this issue—of `alienfx`. From what I see, it appears like the fix is only available on the `master` branch—in commit [`e2894aa`](https://github.com/trackmastersteve/alienfx/commit/e2894aa6197c8639729a97cef55ee1d76e192196)—and it looks like there's some other new work going on in the `master` branch, too.

Can you please create a new incremental release of `alienfx` that contains the fix for this bug?
